spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:clientesdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver


mensaje:
  hola: Hola desde thymeleaf